version: 1

info:
  id: platformsh/koa
  name: Koa
  description: |
      <p>This template demonstrates building the Koa framework for Platform.sh.  It includes a minimalist application skeleton that demonstrates how to connect to a MariaDB server for data storage.  It is intended for you to use as a starting point and modify for your own needs.</p>
      <p>Koa is a lightweight web microframework for Node.js.</p>
  tags:
  - Node.js
  - Framework
  image: data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxMjAiIGhlaWdodD0iNjAiPjxwYXRoIGQ9Ik0zMC4zODcgMTAuNDN2MjMuMjA2bDEwLjI1LTExLjU1N2guNDY3bC03LjU5OCA4LjU3NSAxMC4wMTUgMTQuNzE4aC0zLjI2N2wtOC42MjItMTIuNjg2LTEuMjU3IDEuNDQ3djExLjI0aC0zLjI1MlYxMC40M3ptMjYuNzcgMzUuMTM1cS00LjkyIDAtOC0yLjc5NS0zLjA3LTIuNzk1LTMuMDgyLTguNjIgMC01LjgyNCAzLjE5LTkuMDMgMy4xOS0zLjIwNSA4LjExNC0zLjIzIDQuOTIgMCA4IDIuNzk4IDMuMDcgMi43OTggMy4wNzggOC42MjIgMCA1LjgzLTMuMTkgOS4wNDMtMy4xOSAzLjIxMi04LjExMiAzLjIxNHptLjMwMy0yMy4zMDJxLTMuNTQgMC01Ljg3IDMuMTQ3LTIuMzMgMy4xNDctMi4zMzIgOC43NjcgMCA1LjYxNSAyLjE0MyA4LjMxNyAyLjE0MyAyLjcwMiA1LjY4MiAyLjcwMiAzLjU0IDAgNS44Ny0zLjE0NyAyLjMzMi0zLjE0NyAyLjMzMi04Ljc2IDAtNS42MTUtMi4xNDMtOC4zMTctMi4xNDMtMi43MDItNS42ODYtMi43MDZ6bTMzLjk3IDIzLjEwOHEtMy4xNyAwLTQuMzMzLTEuMjEtMS4wNzMtMS4wMjQtMS4wNzMtMS43OHYtLjk4cS0yLjI4MyA0LjE0OC03LjMxMyA0LjE0OC01Ljg3NiAwLTYuNjY2LTUuMzEyYTYuODgxIDYuODgxIDAgMCAxLS4wOTMtMS4xNDIgNC45OTQgNC45OTQgMCAwIDEgLjE4Ny0xLjI4MnEuMTg1LS43IDEuMDczLTEuNTM2IDEuNzgtMS42OCA3LjgtMi4wNTIgMS40OS0uMTQgMi43NDYtLjE0IDEuMjU1IDAgMi4yODMuMDl2LTcuNzJxLS4wOTMtLjA0NSAwLS40NDVhMS43NTggMS43NTggMCAwIDAtLjE2Mi0xLjAyNCA2LjQ1NCA2LjQ1NCAwIDAgMC0uNjY4LTEuMjM3cS0uNDIzLS42MDUtMS40OS0xLjA0NmE3LjQzMyA3LjQzMyAwIDAgMC0yLjc5NS0uNDQ1IDE1LjYwMSAxNS42MDEgMCAwIDAtNC4wNTEuNjM3cS0yLjMwMy42My0zLjM3NiAxLjIzNWwtLjE4Ny0uMzI3YTE5Ljk3NyAxOS45NzcgMCAwIDEgOC40MzUtMS45MXE0Ljc5NiAwIDYuMzM2IDEuNzI1IDEuMjEgMS4zNSAxLjIxIDIuODQydjE1LjZxMCAxLjM1My41NCAyLjA3NC41NC43MiAxLjA5NS43NjhsLjUxMi4wOTNoMS40NDd2LjM2N3ptLTExLjk3NC0uMTg3YTYuNjU0IDYuNjU0IDAgMCAwIDQuNDUxLTEuN3ExLjk4LTEuNyAyLjEyLTMuMjg1di01LjYzcS0xLjI2Mi0uMTAyLTIuNTQyLS4xMDJhMjMuMDM1IDIzLjAzNSAwIDAgMC0yLjUzNy4xNHEtMy41NDMuNDIzLTQuNjE2IDEuNTg1LTEuMDczIDEuMTYyLTEuMDY4IDMuMjE2YTguMzQ2IDguMzQ2IDAgMCAwIC4wNDUuODM5cS40MTggNC45NDcgNC4xNDYgNC45NDd6IiBmaWxsPSIjMTYxMTFjIi8+PC9zdmc+Cg==

  notes:
    - heading: "Features"
      content: |
          Node.js 14<br />
          MariaDB 10.2<br />
          Automatic TLS certificates<br />
          npm-based build<br />

initialize:
  repository: git://github.com/platformsh-templates/koa.git@master
  config: null
  files: []
  profile: Koa
